{% set name = "daetk" %}
{% set version = "1.0.2" %}
{% set build = 0 %}
{% set sha256 = "8bcc377b59cfa458303a7c85b51db751b023bb368e617ffb1d3b6acba14c9963" %}

{% set mpi = mpi or 'mpich' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: daetk-{{ version }}.tar.gz
  url: https://github.com/erdc-cm/daetk/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - edit_content.patch
    - petscsf.patch

build:
  number: {{ build }}
  skip: true  # [win]
  {% set mpi_prefix = "mpi_" + mpi %}
  string: "{{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}"
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
    - sed
  host:
    - petsc
    - parmetis
    - {{ mpi }}
  run:
    # missing a run_exports section
    - {{ pin_compatible('parmetis', max_pin='x.x') }}
    # these are second-order dependencies that lack a run_exports section
    - hypre
    - scotch
    - scalapack
    - ptscotch
    - metis
    - suitesparse
    - mumps-mpi
    - libopenblas
    - conda-build

test:
  commands:

about:
  home: https://github.com/erdc-cm/daetk
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: The Differential Algebraic Equation Toolkit

extra:
  recipe-maintainers:
    - davidbrochart
    - SylvainCorlay
